#1 Разбиение выборки на обучающую и тестовую
01-task-train-test-split


In [ ]:
import pandas as pd
from sklearn.model_selection import StratifiedShuffleSplit

In [ ]:
# Загружаем датасет
file = "/content/spambase.csv"
df = pd.read_csv(file)

# Разделяем на признаки и целевую переменную
X = df.drop("class", axis=1)
y = df["class"]


In [ ]:
sss_80_20 = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)

for train_index, test_index in sss_80_20.split(X, y):
    X_train_80, X_test_20 = X.iloc[train_index], X.iloc[test_index]
    y_train_80, y_test_20 = y.iloc[train_index], y.iloc[test_index]

print("80/20 split:")
print("Train class distribution:\n", y_train_80.value_counts(normalize=True))
print("Test class distribution:\n", y_test_20.value_counts(normalize=True))


80/20 split:
Train class distribution:
 class
0    0.605978
1    0.394022
Name: proportion, dtype: float64
Test class distribution:
 class
0    0.605863
1    0.394137
Name: proportion, dtype: float64


In [ ]:
sss_70_30 = StratifiedShuffleSplit(n_splits=1, test_size=0.3, random_state=42)

for train_index, test_index in sss_70_30.split(X, y):
    X_train_70, X_test_30 = X.iloc[train_index], X.iloc[test_index]
    y_train_70, y_test_30 = y.iloc[train_index], y.iloc[test_index]

print("\n70/30 split:")
print("Train class distribution:\n", y_train_70.value_counts(normalize=True))
print("Test class distribution:\n", y_test_30.value_counts(normalize=True))



70/30 split:
Train class distribution:
 class
0    0.605901
1    0.394099
Name: proportion, dtype: float64
Test class distribution:
 class
0    0.606083
1    0.393917
Name: proportion, dtype: float64


# 2 Нормализация данных
02-task-standardize-data

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [ ]:
# Загружаем датасет
df = pd.read_csv("wine_types.csv")

# Отделяем признаки и целевую переменную
X = df.drop("Type", axis=1)
y = df["Type"]

# Делим на train/test
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

Модель k-NN без нормализации

In [ ]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)

print("Accuracy без нормализации:", accuracy_score(y_test, y_pred))

Accuracy без нормализации: 0.7407407407407407


Модель k-NN со стандартизацией

In [ ]:
# Стандартизируем данные
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

knn_scaled = KNeighborsClassifier(n_neighbors=5)
knn_scaled.fit(X_train_scaled, y_train)
y_pred_scaled = knn_scaled.predict(X_test_scaled)

print("Accuracy после стандартизации:", accuracy_score(y_test, y_pred_scaled))

Accuracy после стандартизации: 0.9629629629629629


# 3 Линейная алгебра
03-task-linear-algebra

In [ ]:
import numpy as np
import time

In [ ]:
# Вектор a
a = np.array([-8, 15])

# Матрица X
X = np.array([
    [1, 5],
    [3, 4],
    [2, 3]
])

# Скалярное произведение (dot product)
y = np.dot(X, a)

# Поэлементное умножение
z = X * a

print(f"Скалярное произведение y:\n{y}")
print(f"Поэлементное умножение z:\n{z}")

Скалярное произведение y:
[67 36 29]
Поэлементное умножение z:
[[ -8  75]
 [-24  60]
 [-16  45]]


Матрица 10×10

In [ ]:
# Создание матрицы 10x10
A = np.arange(100).reshape(10, 10)
print("Матрица A:\n", A)

Матрица A:
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


Сравнение умножений

In [ ]:
f = np.array([1, 2])
g = np.array([4, 5])

dot_result = np.dot(f, g)
elementwise_result = f * g

print(f"Скалярное произведение (dot): {dot_result}")
print(f"Поэлементное умножение: {elementwise_result}")

Скалярное произведение (dot): 14
Поэлементное умножение: [ 4 10]


Задание 1

In [ ]:
# Исходная матрица A
A = np.array([[1, 2, 3],
              [4, 5, 6]])

# Двойное транспонирование
A_t_t = A.T.T

# Проверка на равенство
print("Исходная матрица A:\n", A)
print("Транспонирование дважды A.T.T:\n", A_t_t)
print("Равны ли матрицы:", np.array_equal(A, A_t_t))

Исходная матрица A:
 [[1 2 3]
 [4 5 6]]
Транспонирование дважды A.T.T:
 [[1 2 3]
 [4 5 6]]
Равны ли матрицы: True


Задание 2

In [ ]:
# Две матрицы одинакового размера
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

# Левая часть уравнения
left = (A + B).T

# Правая часть уравнения
right = A.T + B.T

# Проверка
print("Левая часть (A + B).T:\n", left)
print("Правая часть A.T + B.T:\n", right)
print("Равны ли они:", np.array_equal(left, right))

Левая часть (A + B).T:
 [[ 6 10]
 [ 8 12]]
Правая часть A.T + B.T:
 [[ 6 10]
 [ 8 12]]
Равны ли они: True


Задание 3

In [ ]:
# Квадратная матрица A
A = np.array([[1, 7, 3],
              [0, 5, 9],
              [4, 2, 6]])

S = A + A.T  # Сумма A и A^T
print("Сумма A + A.T:\n", S)

# Проверка симметричности
print("Транспонированная сумма:\n", S.T)
print("Симметрична ли S:", np.array_equal(S, S.T))

Сумма A + A.T:
 [[ 2  7  7]
 [ 7 10 11]
 [ 7 11 12]]
Транспонированная сумма:
 [[ 2  7  7]
 [ 7 10 11]
 [ 7 11 12]]
Симметрична ли S: True


Задание 4

In [ ]:
x = np.zeros((2, 3, 4))

print("Форма тензора x:", x.shape)
print("len(x):", len(x))

print(x[0].shape)  # (3, 4)
print(x[1].shape)  # (3, 4)

Форма тензора x: (2, 3, 4)
len(x): 2
(3, 4)
(3, 4)


Задание 5

In [ ]:
for shape in [(10,), (3, 5), (2, 4, 6), (1, 1, 1, 1)]:
    x = np.zeros(shape)
    print(f"Форма: {shape}, len(x): {len(x)}, x.shape[0]: {x.shape[0]}")

Форма: (10,), len(x): 10, x.shape[0]: 10
Форма: (3, 5), len(x): 3, x.shape[0]: 3
Форма: (2, 4, 6), len(x): 2, x.shape[0]: 2
Форма: (1, 1, 1, 1), len(x): 1, x.shape[0]: 1


Задание 6

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

row_sums = A.sum(axis=1, keepdims=True)  # сохраняем размерность для корректного деления
normalized = A / row_sums

print("Исходная матрица A:\n", A)
print("Сумма по строкам:\n", row_sums)
print("Результат A / A.sum(axis=1):\n", normalized)

Исходная матрица A:
 [[1 2 3]
 [4 5 6]]
Сумма по строкам:
 [[ 6]
 [15]]
Результат A / A.sum(axis=1):
 [[0.16666667 0.33333333 0.5       ]
 [0.26666667 0.33333333 0.4       ]]


Задание 7

In [ ]:
import numpy as np

x = np.ones((2, 3, 4))  # или np.random.rand(...)

print("Исходная форма:", x.shape)
print("Сумма по axis=0:", x.sum(axis=0).shape)
print("Сумма по axis=1:", x.sum(axis=1).shape)
print("Сумма по axis=2:", x.sum(axis=2).shape)

Исходная форма: (2, 3, 4)
Сумма по axis=0: (3, 4)
Сумма по axis=1: (2, 4)
Сумма по axis=2: (2, 3)


Задание 8

In [ ]:
# Тензор размерности (2, 3, 4)
x = np.random.rand(2, 3, 4)

norm = np.linalg.norm(x)

print("Форма тензора:", x.shape)
print("Норма тензора:", norm)

Форма тензора: (2, 3, 4)
Норма тензора: 2.838079536187457


Задание 9

In [ ]:
# Матрицы
A = np.random.randn(210, 216)
B = np.random.randn(216, 25)
C = np.random.randn(25, 214)

# AB -> C
start1 = time.time()
result1 = np.dot(np.dot(A, B), C)
end1 = time.time()

# A -> BC
start2 = time.time()
result2 = np.dot(A, np.dot(B, C))
end2 = time.time()

print("Время (AB)C:", round(end1 - start1, 6), "сек")
print("Время A(BC):", round(end2 - start2, 6), "сек")
print("Результаты идентичны:", np.allclose(result1, result2))

Время (AB)C: 0.001762 сек
Время A(BC): 0.001213 сек
Результаты идентичны: True


Задание 10

In [ ]:
# Матрицы
A = np.random.randn(210, 216)
B = np.random.randn(216, 25)
C = B.T  # Без копии

# AB
start1 = time.time()
result1 = A @ B
end1 = time.time()

# AC^T (т.е. A @ C.T → A @ B)
start2 = time.time()
result2 = A @ C.T
end2 = time.time()

# Сравнение
print("Время A @ B:", round(end1 - start1, 6), "сек")
print("Время A @ C.T:", round(end2 - start2, 6), "сек")
print("Результаты равны:", np.allclose(result1, result2))

# Проверим: C — это ссылка или копия?
print("B is C.T:", B is C.T)  # True — значит, это просто представление, не копия

Время A @ B: 0.000444 сек
Время A @ C.T: 0.00036 сек
Результаты равны: True
B is C.T: False


Задание 11

In [ ]:
# 3 двумерных массива
a = np.random.rand(3, 4)
b = np.random.rand(3, 4)
c = np.random.rand(3, 4)

# Объединение в 3D-тензор
x = np.stack([a, b, c], axis=0)

print("Форма тензора x:", x.shape)

# Извлечение обратно
a2, b2, c2 = x[0], x[1], x[2]

# Проверка
print("Совпадают ли массивы:", np.allclose(a, a2), np.allclose(b, b2), np.allclose(c, c2))

Форма тензора x: (3, 3, 4)
Совпадают ли массивы: True True True


# 4 Работа с данными в PyCaret
04-task-pycaret

In [4]:
pip install --pre pycaret

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 5.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.4/60.4 kB 5.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 169.7/169.7 kB 17.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
INFO: pip is looking at multiple versions of category-encoders to determine which version is compatible with other requirements. This could take a while.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 486.1/486.1 kB 37.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.8/106.8 kB 10.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.8/21.8 MB 73.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.4/85.4 kB 8.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.2/302.2 kB 26.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.3/45.3 kB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 100.8 MB/s eta 0:00:00
   ━

In [1]:
from pycaret.datasets import get_data
from pycaret.regression import *

In [2]:
# Выберем простой регрессионный датасет
data = get_data('insurance')

# Покажем первые строки
data.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [3]:
# Укажем целевую переменную
exp = setup(data, target='charges', session_id=123)

In [4]:
best_model = compare_models()

Processing:   0%|          | 0/81 [00:00<?, ?it/s]

In [6]:
# Посмотрим метрики
evaluate_model(best_model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

In [7]:
save_model(best_model, 'best_insurance_model')

Transformation Pipeline and Model Successfully Saved


(Pipeline(memory=Memory(location=None),
          steps=[('numerical_imputer',
                  TransformerWrapper(include=['age', 'bmi', 'children'],
                                     transformer=SimpleImputer())),
                 ('categorical_imputer',
                  TransformerWrapper(include=['sex', 'smoker', 'region'],
                                     transformer=SimpleImputer(strategy='most_frequent'))),
                 ('ordinal_encoding',
                  TransformerWrapper(include=['sex', 'smoker'],
                                     transfor...
                                                                          'data_type': dtype('O'),
                                                                          'mapping': female    0
 male      1
 NaN      -1
 dtype: int64},
                                                                         {'col': 'smoker',
                                                                          'data_type': dtype(

In [8]:
predictions = predict_model(best_model, data)
predictions[['charges', 'prediction_label']].head()

charges  prediction_label
0  16884.923828      18464.334448
1   1725.552246       4020.345384
2   4449.461914       6555.388388
3  21984.470703       9627.045725
4   3866.855225       3325.531292